version: '3.4'

services:
  jaeger: 
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 14268:14268
      - 16686:16686
  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    ports:
      - 2433:1433
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672